"""
URL mappings for the recipe app.
"""
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from recipe import views

# autogenerates urls for functionality in viewset
router = DefaultRouter()
router.register('recipes', views.RecipeViewSet)
router.register('tags', views.TagViewSet)

app_name = 'recipe'

# includes the urls generated by the router
urlpatterns = [
    path('', include(router.urls)),
]
